GNAY_New1/Controllers/GNAY_ApplicationController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Text;
using System.Web;
using System.Web.Mvc;
using GNAY_New1;
using GNAY_New1.Models;

namespace GNAY_New1.Controllers
{
    public class GNAY_ApplicationController : Controller
    {
        //rzp_test_6GzieAHfpUCJgh
        //6JiXBONvMHa8btXtmMc2NBmH
        private TorqueSolutionsEntities db = new TorqueSolutionsEntities();

        // GET: GNAY_Application
        [Authorize]
        public ActionResult Index()
        {
            return View(db.GNAY_Application.ToList());
        }

        public ActionResult SubmittedMessage()
        {
            return View();
        }

        // GET: GNAY_Application/Details/5
        [Authorize]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            GNAY_Application gNAY_Application = db.GNAY_Application.Find(id);
            if (gNAY_Application == null)
            {
                return HttpNotFound();
            }
            return View(gNAY_Application);
        }

        public ActionResult DrawResult()
        {
            ViewBag.DrawMessage = "";
            return View("DrawResult", new DrawResultModel());
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DrawResult([Bind(Include = "ApplicationNumber")] DrawResultModel drawresult)
        {
            string message = "";

            DateTime timeUtc = DateTime.UtcNow;
            DateTime indiaTime = DateTime.Now;
            try
            {
                TimeZoneInfo indiaZone = TimeZoneInfo.FindSystemTimeZoneById("India Standard Time");
                indiaTime = TimeZoneInfo.ConvertTimeFromUtc(timeUtc, indiaZone);
                message = $"Current date and time are {indiaTime.ToString("dd-MMM-yyyy")} {indiaTime.ToLongTimeString()}.";
            }
            catch (TimeZoneNotFoundException)
            {
                Console.WriteLine("The registry does not define the Central Standard Time zone.");
            }
            catch (InvalidTimeZoneException)
            {
                Console.WriteLine("Registry data on the Central Standard Time zone has been corrupted.");
            }

            if (indiaTime < new DateTime(2021, 6, 25,12,0,0))
            {
                message = message + " Draw results will be available on 25-Jun-2021 after 12 noon. Please check again on/after draw date.";
            }
            else
            {
                var application = db.GNAY_Application.Where(u => u.ApplicationNumber == drawresult.ApplicationNumber).SingleOrDefault();
                if (application == null)
                {
                    message = "Incorrect application number entered!";
                }
                else
                {
                    var result = ConfigurationManager.AppSettings["DrawSuccess"].Split(',');
                    if (result.Contains(drawresult.ApplicationNumber.ToString()))
                        message = $"Congratulations {application.ApplicantName}! Your application is selected by online lucky draw process.";
                    else
                        message = $"Sorry {application.ApplicantName}! Your application is not selected by Lucky draw. Better luck for next time.";
                }
            }

            ViewBag.DrawMessage = message;
            return View("DrawResult", drawresult);
        }

        // GET: GNAY_Application/Create
        public ActionResult Create(string type="")
        {
            if(type != "afterclosed")
                return View("BookingClosed");

            ViewBag.MessageStyle= "margin: 10px 0px 0px 0px; padding: 5px; clear:both; visibility:hidden";
            @ViewBag.ErrorMessage = "";
            ApplicationViewModel obj = new ApplicationViewModel
            {
                AddressProofCopy = "test",
                //DateOfSubmit = DateTime.Today,
                AmountPayable = 1000,
                AnnualIncome = 100000000,
                AnyPreviousLoan = false,
                ApplicantName = "test name",
                ApplicantPhoto = "test",
                ApplicationPaymentID = "12121",
                AppliedProject = "new project",
                CarpetAreaInFoot = 200,
                ClubbedIncomeFamilyMemberName = "test",
                ClubbedmemberAnyPreviousLoan = null,
                ClubbedmemberMonthlyNetIncome = 0,
                ClubbedmemberPreviousLoanBalance = 0,
                ClubbedmemberPreviousLoanEMI = 0,
                CoApplicantAnnualIncome = 0,
                CoApplicantApplicantName = "test",
                ApplicationNumber = 0,
                //ApplicationIPAddress = "1212",
                CoApplicantCommunicationAddress = "test",
                CoApplicantCommunicationPIN = "test",
                CoApplicantCommunicationState = "test",
                CoApplicantContactNumber = "test",
                CoApplicantDepartment = "test",
                CoApplicantDOB = DateTime.Today,
                CoApplicantEmailId = "test",
                CoApplicantFatherName = "test",
                CoApplicantIsNRI = false,
                CoApplicantNationality = "test",
                CoApplicantOccupation = "test",
                CoApplicantOfficeAddress = "test",
                CoApplicantOfficePIN = "12121",
                CoApplicantOfficeState = "test",
                CoApplicantPanNo = "test",
                CoApplicantPermanentAddress = "test",
                CoApplicantPermanentPIN = "test",
                CoApplicantPermanentState = "test",
                CoApplicantPhoto = "test",
                CommunicationAddress = "Chhalera, Sec 44, Noida",
                CommunicationPIN = "12121",
                CommunicationState = "Uttar Pradesh",
                ContactNumber = "1212121",
                Department = "Test Department",
                DOB = Convert.ToDateTime("5/5/1985"),
                EmailId = "luvkushch@gmail.com",
                EmployeeIDCopy = "test",
                FatherName = "Amit Singh",
                IsFirstProperty = true,
                IsNRI = false,
                LoanAmountRequired = 0,
                MonthlyGrossIncome = 100000,
                MonthlyNetIncome = 10000,
                Nationality = "Indian",
                Occupation = "Job",
                OfficeAddress = "Test Address",
                OfficePIN = "444444",
                OfficeState = "U.P.",
                PanCardCopy = "test",
                PanNo = "AWSSDS5656",
                PaymentPlan = "20-30",
                PaymentReceipt = "test",
                PermanentAddress = "Chhalera, Sec 44, Noida",
                PermanentPIN = "12121212",
                PermanentState = "Uttar Pradesh",
                PreviousLoanBalance = 0,
                PreviousLoanEMI = 0,
                RefundAccNo = "sasasa12121",
                RefundBankIFSC = "SDOC3434",
                RefundBankName = "Test bank",
                UnitType = "Plot 150mtr"

            };

            ApplicationViewModel obj1 = new ApplicationViewModel
            {
                AppliedProject = "GNAY",
                PaymentPlan="36 months"
            };

             return View(obj1); //prod
            //return View(obj); //debug
        }


        // POST: GNAY_Application/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ApplicationNumber,ApplicantName,FatherName,Nationality,DOB,IsNRI,PanNo,Occupation,Department,AnnualIncome,EmailId,ContactNumber,CommunicationAddress,CommunicationState,CommunicationPIN,PermanentAddress,PermanentState,PermanentPIN,OfficeAddress,OfficeState,OfficePIN,CoApplicantApplicantName,CoApplicantFatherName,CoApplicantNationality,CoApplicantDOB,CoApplicantIsNRI,CoApplicantPanNo,CoApplicantOccupation,CoApplicantDepartment,CoApplicantAnnualIncome,CoApplicantEmailId,CoApplicantContactNumber,CoApplicantCommunicationAddress," +
            "CoApplicantCommunicationState,CoApplicantCommunicationPIN,CoApplicantPermanentAddress,CoApplicantPermanentState,CoApplicantPermanentPIN,CoApplicantOfficeAddress,CoApplicantOfficeState,CoApplicantOfficePIN,AppliedProject,UnitType,CarpetAreaInFoot,PaymentPlan,AmountPayable,ApplicationPaymentID,PaymentReceipt,RefundAccNo,RefundBankName,RefundBankIFSC,IsFirstProperty,LoanAmountRequired,MonthlyGrossIncome,MonthlyNetIncome,AnyPreviousLoan,PreviousLoanEMI,PreviousLoanBalance,ApplicationIPAddress,ClubbedIncomeFamilyMemberName,ClubbedmemberMonthlyNetIncome,ClubbedmemberAnyPreviousLoan," +
            "ClubbedmemberPreviousLoanEMI,ClubbedmemberPreviousLoanBalance,EmployeeIDCopy," +
            "PanCardCopy,AddressProofCopy,ApplicantPhoto,CoApplicantPhoto,DateOfSubmit,EmployeeIDFile,AddressProofFile," +
            "PanCardFile,ApplicantPhotoFile,CoApplicantPhotoFile,PaymentReceiptFile,BookingAmount")] ApplicationViewModel gNAY_Application)
        {
            

            GNAY_Application obj = new GNAY_Application();

            // Upload documents
            if (gNAY_Application.EmployeeIDFile != null)
            {
                string filename = UploadFile(gNAY_Application.EmployeeIDFile);
                if(filename.Contains("Error:"))
                {
                    ViewBag.ErrorMessage = filename;
                    ViewBag.MessageStyle = "margin: 10px 0px 0px 0px; padding: 5px; clear:both;";
                    return View(gNAY_Application);
                }

                obj.EmployeeIDCopy = filename;

GNAY_New1/Views/GNAY_Application/BookingClosed.cshtml
@{
    ViewBag.Title = "Booking Closed";
}
<section class="about text-center">
    <div class="container">
        <div class="row">
            <h3 style="margin-top:200px">Booking has been closed on 20-Jun-2021. Draw will occur on 25-Jun-2021. Please check on 25-Jun-2021 for draw.</h3>
        </div>
    </div>
</section>

GNAY_New1/Views/GNAY_Application/Delete.cshtml
@model GNAY_New1.GNAY_Application

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>GNAY_Application</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ApplicantName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ApplicantName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FatherName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FatherName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nationality)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nationality)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DOB)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DOB)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsNRI)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsNRI)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PanNo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PanNo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Occupation)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Occupation)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Department)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Department)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AnnualIncome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AnnualIncome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EmailId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EmailId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ContactNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ContactNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CommunicationAddress)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CommunicationAddress)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CommunicationState)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CommunicationState)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CommunicationPIN)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CommunicationPIN)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PermanentAddress)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PermanentAddress)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PermanentState)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PermanentState)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PermanentPIN)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PermanentPIN)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OfficeAddress)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OfficeAddress)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OfficeState)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OfficeState)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OfficePIN)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OfficePIN)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CoApplicantApplicantName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CoApplicantApplicantName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CoApplicantFatherName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CoApplicantFatherName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CoApplicantNationality)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CoApplicantNationality)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CoApplicantDOB)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CoApplicantDOB)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CoApplicantIsNRI)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CoApplicantIsNRI)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CoApplicantPanNo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CoApplicantPanNo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CoApplicantOccupation)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CoApplicantOccupation)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CoApplicantDepartment)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CoApplicantDepartment)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CoApplicantAnnualIncome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CoApplicantAnnualIncome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CoApplicantEmailId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CoApplicantEmailId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CoApplicantContactNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CoApplicantContactNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CoApplicantCommunicationAddress)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CoApplicantCommunicationAddress)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CoApplicantCommunicationState)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CoApplicantCommunicationState)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CoApplicantCommunicationPIN)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CoApplicantCommunicationPIN)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CoApplicantPermanentAddress)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CoApplicantPermanentAddress)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CoApplicantPermanentState)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CoApplicantPermanentState)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CoApplicantPermanentPIN)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CoApplicantPermanentPIN)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CoApplicantOfficeAddress)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CoApplicantOfficeAddress)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CoApplicantOfficeState)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CoApplicantOfficeState)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CoApplicantOfficePIN)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CoApplicantOfficePIN)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AppliedProject)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AppliedProject)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UnitType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UnitType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CarpetAreaInFoot)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CarpetAreaInFoot)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PaymentPlan)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PaymentPlan)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AmountPayable)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AmountPayable)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ApplicationPaymentID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ApplicationPaymentID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PaymentReceipt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PaymentReceipt)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RefundAccNo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RefundAccNo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RefundBankName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RefundBankName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RefundBankIFSC)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RefundBankIFSC)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsFirstProperty)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsFirstProperty)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LoanAmountRequired)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LoanAmountRequired)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MonthlyGrossIncome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MonthlyGrossIncome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MonthlyNetIncome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MonthlyNetIncome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AnyPreviousLoan)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AnyPreviousLoan)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PreviousLoanEMI)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PreviousLoanEMI)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PreviousLoanBalance)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PreviousLoanBalance)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ApplicationIPAddress)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ApplicationIPAddress)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ClubbedIncomeFamilyMemberName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ClubbedIncomeFamilyMemberName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ClubbedmemberMonthlyNetIncome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ClubbedmemberMonthlyNetIncome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ClubbedmemberAnyPreviousLoan)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ClubbedmemberAnyPreviousLoan)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ClubbedmemberPreviousLoanEMI)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ClubbedmemberPreviousLoanEMI)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ClubbedmemberPreviousLoanBalance)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ClubbedmemberPreviousLoanBalance)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EmployeeIDCopy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EmployeeIDCopy)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PanCardCopy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PanCardCopy)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AddressProofCopy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AddressProofCopy)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ApplicantPhoto)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ApplicantPhoto)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CoApplicantPhoto)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CoApplicantPhoto)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateOfSubmit)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateOfSubmit)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

GNAY_New1/Views/GNAY_Application/DrawResult.cshtml
@model GNAY_New1.Models.DrawResultModel
@{
    ViewBag.Title = "Draw Result";
}
<section class="about text-center">
    <div class="container">
        <div class="row" style="margin-top:200px">
            @using (Html.BeginForm("DrawResult", "GNAY_Application", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
            {
                @Html.AntiForgeryToken()
                <h4>Enter your application Id</h4>
                <hr />
                @Html.ValidationSummary("", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(m => m.ApplicationNumber, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.ApplicationNumber, new { @class = "form-control" })
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" class="btn btn-default" value="Submit" />
                    </div>


                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        @if (ViewBag.DrawMessage != "")
                        {
                            <div class="alert alert-info" style="font-family:Verdana">@ViewBag.DrawMessage</div>
                        }
                    </div>
                </div>
            }

            @section Scripts {
                @Scripts.Render("~/bundles/jqueryval")
            }
        </div>
    </div>
</section>

GNAY_New1/Views/GNAY_Application/PaymentPage.cshtml
@{
    Layout = null;
}

@model GNAY_New1.Controllers.OrderModel
<!-- // Click this button automatically when this page load using javascript -->
<!-- You can hide this button -->
<button id="rzp-button1" hidden>Pay</button>
<script src="https://checkout.razorpay.com/v1/checkout.js"></script>
<script>
var options = {
    "key": "@Html.DisplayFor(model => model.razorpayKey)", // Enter the Key ID generated from the Dashboard
    "amount": "@Html.DisplayFor(model => model.amount)", // Amount is in currency subunits. Default currency is INR. Hence, 50000 refers to 50000 paise
    "currency": "@Html.DisplayFor(model => model.currency)",
    "name": "@Html.DisplayFor(model => model.name)",
    "description": "@Html.DisplayFor(model => model.description)",
    "image": "Content/img/2019/10/GNAY_logo.png", // You can give your logo url
    "order_id": "@Html.DisplayFor(model => model.orderId)",
    "handler": function (response){
        // After payment successfully made response will come here
        // Set the data in hidden form
        document.getElementById('rzp_paymentid').value = response.razorpay_payment_id;
        document.getElementById('rzp_orderid').value = response.razorpay_order_id;

        // // Let's submit the form automatically
        document.getElementById('rzp-paymentresponse').click();
    },
    "prefill": {
        "name": "@Html.DisplayFor(model => model.name)",
        "email": "@Html.DisplayFor(model => model.email)",
        "contact": "@Html.DisplayFor(model => model.contactNumber)"
    },
    "notes": {
        "address": "@Html.DisplayFor(model => model.address)"
    },
    "theme": {
        "color": "#F37254"
    }
};
var rzp1 = new Razorpay(options);

//<!-- onload function -->
window.onload = function(){
    document.getElementById('rzp-button1').click();
};

document.getElementById('rzp-button1').onclick = function(e){
    rzp1.open();
    e.preventDefault();
}
</script>
<!-- This form is hidden, and submit when payment successfully made -->
@using (Html.BeginForm("Complete", "GNAY_Application"))
{
    @Html.AntiForgeryToken()

    @Html.Hidden("rzp_paymentid")
    @Html.Hidden("rzp_orderid")
    <button type="submit" id="rzp-paymentresponse" class="btn btn-primary" hidden>Submit</button>
}

GNAY_New1/Views/GNAY_Application/SubmittedMessage.cshtml
@{
    ViewBag.Title = "SubmittedMessage";
}
<section class="about text-center">
    <div class="container">
        <div class="row">
            <h3 style="margin-top:200px">@ViewBag.message</h3>
        </div>
    </div>
</section>